[project]
name = "writing-bot"
version = "0.1.0"
description = ""
authors = [
    {name = "Stephane Burwash",email = "stefburwash@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "gqlalchemy (==1.7.0)",
    "memgraph (>=0.0.1,<0.0.2)",
    "click (>=8.2.1,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
